Echos

diff --git a/.github/workflows/rezip.yml b/.github/workflows/rezip.yml
--- a/.github/workflows/rezip.yml
+++ b/.github/workflows/rezip.yml
@@ -4,8 +4,7 @@ on:
   pull_request:
 
 env:
-  FNAME2: ${(find . -name '*.zip' | head -1 | cut -d / -f 2)}
-  FNAME: "EVN TEST"
+  ENV1: Just string, we can't do somethink like $(echo "this")
 
 jobs:
   copy_files_job:
@@ -18,23 +17,37 @@ jobs:
 #        run: echo ::set-output name=FNAME::$(find . -name '*.zip' | head -1 | cut -d / -f 2)
       - name: Set VAR
         run: echo "{FNAME}={$(find . -name '*.zip' | head -1 | cut -d / -f 2)}" >> $GITHUB_ENV
-      - name: All script
-        run:  | 
-          sudo apt update && sudo apt-get install unzip -y zip;
-          mv *.zip work.zip;
-          unzip work.zip -d rezip;
-          find . -name "*.debug" -exec rm {} \; 
-          find . -name "*.sym" -exec mv {} *.so find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
-          cd rezip &&  zip -9 -r work.zip * && mv work.zip ../work.zip && rm -r ../rezip && echo 'Reziped!';
+      - name: Show me VAR
+        run: |
+          echo ${{ env.FNAME }};
+          echo ${{ env.ENV1 }};
+          echo ${ env.FNAME };
+          echo ${ FNAME };
           echo $FNAME;
-          echo ${{ env.FNAME2 }};
-          cd ../ && mv work.zip ${{ env.FNAME2 }} || echo "ERRORishe"
-        shell: bash
-        env: 
-          FNAME:  ${{ env.FNAME }}
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: processed-symbols
-          path:  ${{ env.FNAME2 }}
-          retention-days: 7
+          echo $FNAME2;
+          echo $FNAME3;
+          echo =====
+        env:
+          FNAME2: ${{ env.FNAME }}
+          FNAME3: ${{ GITHUB_ENV.FNAME }}
+
+#      - name: All script
+#        run:  | 
+#          sudo apt update && sudo apt-get install unzip -y zip;
+#          mv *.zip work.zip;
+#          unzip work.zip -d rezip;
+#          find . -name "*.debug" -exec rm {} \; 
+#          find . -name "*.sym" -exec mv {} *.so find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
+#          cd rezip &&  zip -9 -r work.zip * && mv work.zip ../work.zip && rm -r ../rezip && echo 'Reziped!';
+#          echo $FNAME;
+#          echo ${{ env.FNAME2 }};
+#          cd ../ && mv work.zip ${{ env.FNAME2 }} || echo "ERRORishe"
+#        shell: bash
+#        env: 
+#          FNAME:  ${{ env.FNAME }}
+#      - name: Upload Artifact
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: processed-symbols
+#          path:  ${{ env.FNAME2 }}
+#          retention-days: 7
