what the luck

diff --git a/.github/workflows/rezip.yml b/.github/workflows/rezip.yml
--- a/.github/workflows/rezip.yml
+++ b/.github/workflows/rezip.yml
@@ -26,8 +26,9 @@ jobs:
           find . -name "*.debug" -exec rm {} \; 
           find . -name "*.sym" -exec mv {} *.so find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
           cd rezip &&  zip -9 -r work.zip * && mv work.zip ../work.zip && rm -r ../rezip && echo 'Reziped!';
-          cd ../ && mv work.zip ${{ env.FNAME2 }} 
-          echo $FNAME
+          echo $FNAME;
+          echo ${{ env.FNAME2 }};
+          cd ../ && mv work.zip ${{ env.FNAME2 }} || echo "ERRORishe"
         shell: bash
         env: 
           FNAME:  ${{ env.FNAME }}
